### ISSUE TITLE
用了一段时间发现几个小问题

### ISSUE THREAD

**Issue by davidwang558** [SnailDove/deskmini-h310#2]
efi我只改了三码信息，其他都没动，用了一段时间，发现几个小问题：
1. dock下面会水波纹，白色背景下很明显（显示器是好的，hdml和dp口都这样）
2. 两个耳机插孔都不能用
3. 同款网卡不知道是不是转接卡的关系，会有点顶到m2固态，这样长期使用会不会因为固态散热把网卡弄坏

**Comment by koor** [comment]
efi用这个[https://github.com/hackintosh-club/ASRock-DeskMini-310](https://github.com/hackintosh-club/ASRock-DeskMini-310)，完美驱动。
固态芯片都在正面，背面不发热，我用了好几年没出问题

**Comment by davidwang558** [comment]
@koor 设备已经吃灰很久了 还是非常感谢哈
